import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=1"],
    // apple: ["/apple-icon.png"],
    // shortcut: ["/apple-icon.png"],
  },
};

// export const metadata = {
//   metadataBase: new URL('https://www.webeelanguages.com/'),
//   title: "Learn Languages Online with WeBee Language Institute",
//   description:
//     "Master Mandarin, Spanish, English & More! WeBee offers online language courses for Adults & Children. Learn from anywhere, achieve fluency & connect globally! ",
//   icons: {
//     icon: ["/favicon.ico?v=1","/icon1.png","/icon2.png","/icon3.png"],
//     apple: ["/apple-icon.png"],
//     shortcut: ["/apple-icon.png"],
//   },
//   openGraph: {
//     title: "Learn Languages Online with WeBee Language Institute",
//     description:
//       "Master Mandarin, Spanish, English & More! WeBee offers online language courses for Adults & Children. Learn from anywhere, achieve fluency & connect globally! ",
//     url: "https://www.webeelanguages.com/",
//     site_name: "WeBee Language Institute",
//     images: [
//       {
//         url: "/opengraph-image.png",
//         type: "image/png",
//         secureUrl: "/opengraph-image.png",
//         alt: "webee open graph image",
//       }
//     ],
//     locale: "en_US",
//     type: "website",
//   },
//   manifest: "/site.webmanifest",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
